#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_new_controller:
  path: /
  controller: App\Controller\NewController::homepage

app_new_controller2:
  path: /list
  controller: App\Controller\NewController::something

app_task_controller:
  path: /forms
  controller: App\Controller\TaskController::new

app_task-manager_controller:
  path: /list/manager
  controller: App\Controller\TaskController::delete

app_status-edit_controller:
  path: /list/status_edit/{id}
  controller: App\Controller\NewController::edit_status

app_game_controller:
  path: /game
  controller: App\Controller\GameController::mainscreen

app_game_1_controller:
  path: /game/1
  controller: App\Controller\GameController::load_1

app_list_dx_controller:
  path: /list/dx
  controller: App\Controller\ListController::list_dx

app_list_dx_data_controller:
  path: /list/dx/data
  controller: App\Controller\ListController::list_dx_data
